### ISSUE TITLE
Add Damage tracking

### ISSUE THREAD

**Issue by phantompatrol** [umts/probable-engine#111]
We would like the ability to track damage per vehicle.

Idea: When an Incidental occurs (based on type) create a record of damage on the cart. Theoretical models would include:

Damage Type:
- ~~Name~~ inherits from incurred_incidental

Damage:
- ~~Cart Id~~ inherits from incurred_incidental
- ~~Damage Type~~ will be too dynamic, should use text field
- ~~Rental Id?~~ inherits from incurred_incidental
- Estimated Cost to repair
- Actual Cost to repair
- ~~Reservation used to make the repair (time used by a mechanic)~~ hold
- Date of Damage
- Date of Repair
- User who made repair
- ~~Description (text)~~ use this instead of damage type
- Location of incident
- ~~Comments (non public?),~~ can take place on incidental

May live in the API, or may live on the app.

**Comment by xliu3** [comment]
working on it!

**Comment by xliu3** [comment]
Need to follow up with the Damage Object Feature with @dfaulken 

There is a some written code in the following pull request.
https://github.com/umts/aggressive-epsilon/pull/32

**Comment by tomecho** [comment]
@anmerkl will be handling this

**Comment by tomecho** [comment]
https://github.com/anmerkl/probable-engine/tree/damage-tracking

**Comment by tomecho** [comment]
this really ought to inherit from incurred_incidental
