### ISSUE TITLE
Refactor financial_transaction_spec

### ISSUE THREAD

**Issue by phantompatrol** [umts/probable-engine#117]
There is some verbose code in the [financial_transaction_spec](https://github.com/umts/probable-engine/blob/master/spec/models/financial_transaction_spec.rb), that could use a touch up.

Examples: `valid_rental = create :rental, item_type: @item_type` While correct, we have an association setup to [create an item_type](https://github.com/umts/probable-engine/blob/master/spec/factories/rental.rb#L5), along with a rental. Ends up being a bit WET.

Further, [some lines](https://github.com/umts/probable-engine/blob/master/spec/models/financial_transaction_spec.rb#L38) are a [bit long](https://github.com/umts/probable-engine/blob/master/spec/models/financial_transaction_spec.rb#L57) and line breaks would add a lot of readability.

**Comment by Cobchise** [comment]
Commit added to address this in #115
