### ISSUE TITLE
Damage Reservation creation

### ISSUE THREAD

**Issue by xliu3** [umts/probable-engine#156]
## APP part
- need to assign a specific item/cart to API
- need to re-assign new item/cart to the customer if the damaged item/cart was rented during the repair time period
- need to cancel the rental reservation if there is no other available item to be replace
- need to send a notice if the rental reservation is cancel

---
## API part
- create damage reservation creation logic

**Comment by anmerkl** [comment]
@owlee Dibs.

**Comment by tomecho** [comment]
duplicate of #111
