### ISSUE TITLE
'Create Incurred Incidental' button in Incidental Type show view does not work

### ISSUE THREAD

**Issue by anmerkl** [umts/probable-engine#162]
Creating a new incurred incidental requires rental_id.
'Create Incurred Incidental' button in Rental show view is hooked up to send rental_id as param.
'Create Incurred Incidental' button in Incidental Type show view does not do this, so creating a new incurred incidental fails.

Update button to send rental_id as param like in Rental.
or remove 'Create Incurred Incidental' button in Incidental Type altogether?

**Comment by tomecho** [comment]
It seems to work fine for me.  It doesn't pass the rental id from that page because it doesnt have it.  But the rental is selectable on the 'new incurred incidental page'.
[[ http://g.recordit.co/CfTpQO2eEY.gif | height = 400px ]]

**Comment by anmerkl** [comment]
You right.  I was poking around in my feature branch instead of master.
