### ISSUE TITLE
rental revisited

### ISSUE THREAD

**Issue by tomecho** [umts/probable-engine#172]
# show
* change status to be human readable (remove under score)
* remove date range from title
* rearrange fields
  * billing information at the top
  * details at the bottom
* rename payment summary to financial transactions
  * payments should be negative values (may be the current behavior)

# index
* display canceled rentals in a readable color

# transform (process)
* check out
  * add pick up customer information (text field)
  * ability to change contact information
  * default fully charged and confirmed return time to yes
* check in
  * add drop off customer information (text field)
  * overdue rentals should actually be checked it, right now the form does nothing
  * report incurred incidentals
# general
* add fields to mode
  * reserved by (rename user name)
  * picked up by (text field)

**Comment by Cobchise** [comment]
@tomecho I believe the rental show already has a user readable status (I think this was changed in my styling PR which is now included in invoices) but @owlee dibs

**Comment by tomecho** [comment]
![image](https://cloud.githubusercontent.com/assets/2114323/18639770/2e2463a8-7e63-11e6-89d5-47dfac0fd4bd.png)
versus 

![image](https://cloud.githubusercontent.com/assets/2114323/18639794/4239f9c0-7e63-11e6-944a-1e1723944871.png)

**Comment by Cobchise** [comment]
Ah my mistake, I only checked 'Reserved' status which of course is not hyphenated
