### ISSUE TITLE
Finish 'documents' model

### ISSUE THREAD

**Issue by anmerkl** [umts/probable-engine#182]
# Finish implementing 'documents' model

Looks like the current 'documents' model is only a placeholder, as it only has a filename column
- 'documents' needs to be finished to actually store a file in the database
- Make new documents model polymorphic (see 'notes' table for reference)
### Add documents to incurred incidentals
- Remove the 'incurred_incidentals_documents' table
- Use new polymorphic 'documents' instead

**Comment by tomecho** [comment]
are we actually storing in the database or are we using the filesystem, this line
![image](https://cloud.githubusercontent.com/assets/2114323/20807053/610b1ca2-b7cb-11e6-9621-e72036070260.png)
seems to suggest that we are actually sotring directly in the file system, which unless im mistaken is probably the better way to store images (source, [facebook whitepage](http://perspectives.mvdirona.com/2008/06/facebook-needle-in-a-haystack-efficient-storage-of-billions-of-photos/)
