### ISSUE TITLE
Creating Rentals Before Current Day

### ISSUE THREAD

**Issue by Cobchise** [umts/probable-engine#183]
This should be disabled. Currently when attempted results in unfriendly error

**Comment by tomecho** [comment]
relation #70

**Comment by owlee** [comment]
I will take a look at it since it is in vicinity of my PR #192

**Comment by tomecho** [comment]
this is an ongoing development in #70. @owlee do you want to assume the responsibility of #70 as well? I should probably take it but if you already did it let me know.
