### ISSUE TITLE
Financial Transactions

### ISSUE THREAD

**Issue by jgthibodeau** [umts/probable-engine#19]
To handle all fees and adjustments we will be using a financial transactions model

A rental will be linked to multiple financial transactions
Each transaction will have the rental_uid, a type (rental_fee, incidental, adjustment, or payment), the amount, an adjustment, and a note field

When a rental is made
- a financial_transaction will be created on it using the fee_schedule for this item_type

When a rental is checked in
- incidentals will be noted, creating an incurred_incidental object and a financial_transaction using the fees in the incidental_type

A rental can have adjustments applied
- these financial transactions are essentially coupons which will have negative amounts

Financial transactions can be adjusted to increase/decrease the amount, and to cancel out the value entirely without deleting the transaction itself

**Comment by owlee** [comment]
:point_left:

**Comment by phantompatrol** [comment]
Done!
