### ISSUE TITLE
Help Diagnosing!

### ISSUE THREAD

**Issue by owlee** [umts/probable-engine#190]
Any idea what is causing the 404? I did a pull to master and now it is throwing this..... It refers to Rails 5, might be something with depreciation. @tomecho @Cobchise 

<img width="1279" alt="screen shot 2016-10-04 at 3 40 06 pm" src="https://cloud.githubusercontent.com/assets/6244202/19089586/ee0b3d54-8a48-11e6-8ff9-913b0be23289.png">

**Comment by tomecho** [comment]
From `app/controllers/application_controller.rb`

![image](https://cloud.githubusercontent.com/assets/2114323/19120877/7b011bf8-8af2-11e6-9506-b41368ddc883.png)

You cannot pass `nothing: true` anymore 
fixed by #191

**Comment by owlee** [comment]
Cool! We just need to merge then. Ill look it over.
