### ISSUE TITLE
Home page visual glitch

### ISSUE THREAD

**Issue by tomecho** [umts/probable-engine#194]
On initial load the home page shows the _upcoming rentals_ tab highlighted but it is not really the selected tab.  The selected tab is actually the _all rentals_ tab.  The initial tab is supposed to be _upcoming rentals_ (it should be highlighted and selected on initial page load)

![image](http://g.recordit.co/L297KAs8Xg.gif)

**Comment by owlee** [comment]
It seems fine on mine. Did you test on master?

**Comment by Cobchise** [comment]
Seems fine on mine too. I tested on both master and my 'rental_revisited' branch and it works as it should on both

**Comment by tomecho** [comment]
hmm this isnt on master, i think i merged someone's branch. the default should be upcoming rentals anyway.

**Comment by tomecho** [comment]
yep i merged `remotes/cobchise/rental_revisited` and reproduced the error

**Comment by Cobchise** [comment]
[Fixed](https://github.com/Cobchise/probable-engine/blob/0333d0639101f8b2619fa234fa3b11c867bcb00c/app/views/home/index.html.erb#L16-L24) in PR #188
