### ISSUE TITLE
Correct usage of back buttons

### ISSUE THREAD

**Issue by anmerkl** [umts/probable-engine#197]
Some 'Back' buttons, such as in form pages, link to a specific page such as index or show pages instead of using the traditional browser back action as would be expected. 
Change all such instance to make more sense.

Back buttons should be encoded as:
`<%= link_to 'Back', :back, class: "btn btn-default" %>`

**Comment by tomecho** [comment]
`^(.)*link_to 'Back'..(?!:back)(.)*$`
