### ISSUE TITLE
Exclude Rubocop from Travis?

### ISSUE THREAD

**Issue by dfaulken** [umts/probable-engine#20]
One thing I did last week that may work more nicely for you is that I droppped RuboCop from Travis. What @werebus pointed out was that bad style doesn't mean the code is broken or shouldn't be deployed - just that there's an issue that needs to be looked at, but isn't impeding functionality. This makes CodeClimate the more natural place to deal with RuboCop failures.

In particular, causing builds to pass with a `.rubocop_todo.yml` file means that CodeClimate won't report on those issues, which means you miss out on the nice GitHub issue integration, and it's easier to lose track of the problems. Arguably, it also means your GPA is wrong.

(Personally, if I ran CodeClimate, I'd have the `fixme` engine flag a `.rubocop_todo.yml` file as a problem - I don't like to deploy them. But I recognize that that's a matter of personal preference and not of convention).

**Comment by jgthibodeau** [comment]
I think I agree with that. I like the idea of forcing good styling, but at the same time it shouldnt mean that the build is failing (it just isnt as nice as it could be). Also when some unavoidably complex code shows up it will have to be ignored which could lead to a cascade of ignored problems that need to be revisited but may never be.

**Comment by dfaulken** [comment]
If you're interested in still flagging bad style as a problem, the CodeClimate pull request integration is a good way to go.
