### ISSUE TITLE
FinancialTransaction.adjustments

### ISSUE THREAD

**Issue by tomecho** [umts/probable-engine#200]
Should this field be used to modify the amount field, currently the cost of a financial transaction is just the amount, it doesnt look like this field is in use.  Should flexible pricing be useing this cost adjustment?

**Comment by tomecho** [comment]
@phantompatrol @owlee

**Comment by owlee** [comment]
It could be blown away or left alone. I don't see any harm either way, but, may or may not be useful in the future.

**Comment by owlee** [comment]
![Alt Text](https://media.giphy.com/media/KVUhxQAqrAV3i/giphy.gif)
