### ISSUE TITLE
incurred_incidental#show format data in user friendly way

### ISSUE THREAD

**Issue by tomecho** [umts/probable-engine#232]
![image](https://cloud.githubusercontent.com/assets/2114323/22436142/e828b740-e6f0-11e6-97d0-49779e77e639.png)
- Show amount with dollar sign hint use `number_to_currency`
- format dates

**Comment by josephkelley** [comment]
We also have date/currency beautification work to do in:
- the financial transaction table
- incurred_incidentals#index
- payment tracking

How would we like to format dates? In the screenshot above, we have two different stylings (Mon dd,time and yyyy-mm-dd). I get why that's the case above, seems reasonable in context, but there are other places in the app where we use mm-dd-yyyy and mm/dd/yyyy, and it would probably be best to narrow that down to one or two variations in formatting.

Maybe "Mon dd, yyyy time" for notes like above (or whenever time relevant?) and "mm-dd-yyyy" for all other dates?

**Comment by dfaulken** [comment]
> Maybe "Mon dd, yyyy time" for notes like above (or whenever time relevant?) and "mm-dd-yyyy" for all other dates?

I can't think of any reason to represent a date differently when it's paired with a time.

**Comment by josephkelley** [comment]
I just liked the way it looked in the Notes box in @tomecho's screenshot above, but for simplicity's sake I'll make it mm-dd-yyyy everywhere.

**Comment by dfaulken** [comment]
http://ux.stackexchange.com/questions/16095/how-to-display-date-and-time
