### ISSUE TITLE
Terms and Conditions box is too large

### ISSUE THREAD

**Issue by josephkelley** [umts/probable-engine#235]
This is a small CSS issue, but the terms and conditions box is sized to fit all possible disclaimers as opposed to just the active one.

<img width="782" alt="screen shot 2017-01-31 at 12 36 54 pm" src="https://cloud.githubusercontent.com/assets/7460637/22476935/32505dd4-e7b2-11e6-8711-91fb37f71626.png">

**Comment by owlee** [comment]
Ignore this. I have a branch to remove this in favor of document links with the disclaimer.
