### ISSUE TITLE
Rental Reservation: Saving Dates is broken

### ISSUE THREAD

**Issue by owlee** [umts/probable-engine#239]
When you reserve a rental from date A to date B, the dates don't seem to be stored correctly. The reservation show page does not display the dates and the calendar (rentals index) does not display the date range over X days on the calendar.

Start date does seem to be saved though.

**Comment by owlee** [comment]
Edit: The end date is saved as the start date.

**Comment by tomecho** [comment]
It looks like the end date and start date are saved fine for the rental
![image](https://cloud.githubusercontent.com/assets/2114323/23811104/82731dac-05a2-11e7-9ce5-fa32abe4a28d.png)

![image](https://cloud.githubusercontent.com/assets/2114323/23811096/78c01058-05a2-11e7-836d-6ff64e67781c.png)


This is probably an old issue
