### ISSUE TITLE
unable to view user

### ISSUE THREAD

**Issue by tomecho** [umts/probable-engine#250]
![image](https://cloud.githubusercontent.com/assets/2114323/22987818/1b10b218-f37e-11e6-899c-94179c8cec68.png)

**Comment by tomecho** [comment]
![image](https://cloud.githubusercontent.com/assets/2114323/22987893/440b545c-f37e-11e6-8294-b5dcb9870403.png)

**Comment by josephkelley** [comment]
This occurs on a call to `@user.department.name`. Is department required?

**Comment by tomecho** [comment]
fixed by #272
