### ISSUE TITLE
Periodic ItemType import script from aggressive-epsilon to probable-engine

### ISSUE THREAD

**Issue by tomecho** [umts/probable-engine#258]
ItemTypes are a loose connection between probable-engine and aggressive-epsilon, probable-engine must sync with aggressive-epsilon to receive any new item types.  It should be noted aggressive-epsilon is the authority on item types, by default a created item type on probable engine does not sync with the database.  Importing item types from aggressive epsilon should happen periodically.

**Comment by tomecho** [comment]
or maybe just a refresh button like on items page, and then the ability to create item types with a form.

**Comment by Cobchise** [comment]
Whilst working on this I've noticed that currently the API does not store information such as 'base_fee' and 'fee_per_day' for Item_Types whereas the local db does? This makes it difficult to have an import script as we have no way of keeping fees for item types in sync. I think we should add fees to the API as well as local.

**Comment by tomecho** [comment]
The idea was that the api doesn't care about pricing and would be used to
store things which dont have an associated price like the transit busses.
It wouldn't cost money to reserve these things.
