### ISSUE TITLE
Items import does not work

### ISSUE THREAD

**Issue by tomecho** [umts/probable-engine#259]
It doesnt seem to be importing items in production.

**Comment by Cobchise** [comment]
It seems to be a problem with the 'refresh_items_helper' when it's reaching out to the API, works in development just fine. I believe this may be being caused by out of sync UUID's of item types between production and the API, but I can't say for sure as I can't see the db

**Comment by Cobchise** [comment]
Confirmed: performing a tail -f of the production.log and then trying to do an item import resulted in the following:
```
(0.5ms)  BEGIN
SQL (0.9ms)  INSERT INTO `items` (`name`, `item_type_id`, `uuid`, `created_at`, `updated_at`) VALUES ('test5', '2', '3a1960b6-fb35-4559-8149-c1b7dea95147', '2017-12-05 20:14:56', '2017-12-05 20:14:56')
(0.5ms)  ROLLBACK
```
The issue here being it's trying to import an item with a item_type_id that doesn't exist
