### ISSUE TITLE
flash message after user creation warning that new user has no permissions

### ISSUE THREAD

**Issue by tomecho** [umts/probable-engine#296]

**Comment by nawilliams** [comment]
It might make sense to add a hyperlink in the flash message pointing to the groups page.

There's also a fair bit of inconsistency in the capitalization of flash messages. It looks like a quarter of them have Every Letter Capitalized, but most Just have the first letter capitalized. Do we want to make them uniform?

**Comment by owlee** [comment]
Arbitrary with hyperlink... If you have the power to create users, you probably know how to add permissions.

Maybe change the flash message to something like... "User requires admin action to update permissions and groups" . I believe only admins can access permissions and groups anyways. Not sure about user creation, but believe its admins only.

Please fix inconsistencies 👍 Let's do sentence flash messages if we're being more descriptive.
