### ISSUE TITLE
Incidental management

### ISSUE THREAD

**Issue by jgthibodeau** [umts/probable-engine#3]
Incidental management needs to be built up and tested

**Comment by phantompatrol** [comment]
Please see https://github.com/umts/probable-engine/wiki/Schema

**Comment by jgthibodeau** [comment]
Please re-check the schema page, it has been updated to match todays code review which involved a change to financial_transactions.

Incurred incidentals will not keep track of fees, this will be built into financial transactions. When checking in, incurred incidentals will be created to keep track of history on a vehicle and a transaction will be created using the fees from the incidental type

Incurred incidentals will also have either a document field, or link to documents, allowing photos to be saved

**Comment by tomecho** [comment]
hmm just read this after i finished it :frowning: although I have read the schema again and the incidental_type still has a base and a modifier_amount.  Is that not related to the fee's?
