### ISSUE TITLE
Back buttons between View and Edit link to each other after Update

### ISSUE THREAD

**Issue by nawilliams** [umts/probable-engine#300]
This creates an infinite loop if you first click View and then click the edit button from that page, then click the update button. When you click update it redirects you to the show page. As a result link_to :back on the show page points to the edit page and vice versa.

**Comment by owlee** [comment]
Is this from the Rentals controller?

**Comment by nawilliams** [comment]
This is for all controllers.

**Comment by nawilliams** [comment]
Wrong button. 😱

**Comment by nawilliams** [comment]
![ezgif-3-81ccd99ee1](https://cloud.githubusercontent.com/assets/23364580/24426856/09244f50-13d7-11e7-9673-67f210f0c97a.gif)
Bug in action.

**Comment by owlee** [comment]
Yup understood. The :back key on the show should return to controller#index instead. We want to keep the functionality of returning back to show#id from an edit.

**Comment by nawilliams** [comment]
Bug happens in safari only after clicking update, and retains the looping bug for only that id. It always loops in chrome.
