### ISSUE TITLE
Should we remove the tabbed tables on rental#show?

### ISSUE THREAD

**Issue by josephkelley** [umts/probable-engine#332]
Since we're unlikely to have an overwhelming number of incurred incidentals, I think it would make more sense to display these tabbed tables one after another. This would allow users to see the big "Total Amount Due" as well as the pricing breakdown without having to do any clicking.

<img width="1166" alt="screen shot 2017-04-19 at 4 31 56 pm" src="https://cloud.githubusercontent.com/assets/7460637/25200932/2e7c6208-251e-11e7-8c78-4d8487031837.png">
<img width="1144" alt="screen shot 2017-04-19 at 4 34 20 pm" src="https://cloud.githubusercontent.com/assets/7460637/25200933/2e7fd578-251e-11e7-9a31-ab9a9a8e21e1.png">

**Comment by tomecho** [comment]
i think its fine if you want to

**Comment by owlee** [comment]
It doesn't matter with me because if you print the copy, the incurred_incidentals and financial_trans are stacked with each other already. If anything, I think it would be better to have financial_transactions 'active' or first in the the tabbed tables.

**Comment by josephkelley** [comment]
How does this look to y'all?

<img width="933" alt="screen shot 2017-04-24 at 11 46 40 am" src="https://cloud.githubusercontent.com/assets/7460637/25345762/c836a8c2-28e3-11e7-8c42-69beed71f7f2.png">

**Comment by tomecho** [comment]
:eyes: 👍  :2nd_place_medal: 👱
