### ISSUE TITLE
Rental#create is taking a long time

### ISSUE THREAD

**Issue by tomecho** [umts/probable-engine#374]
It seems like the problem is because of the views taking forever to render, i'd bet at least part of that is the mail, we are already delivering async with deliver_later but it seems like it still tries to render right away. I think the reason is explained here, https://stackoverflow.com/a/28780106/4463703

`Completed 200 OK in 30894ms (Views: 30733.9ms | ActiveRecord: 115.1ms)`

Sucker punch seems like it would work fine for our application and is self contained which makes things simple.  https://github.com/brandonhilkert/sucker_punch

Installing is easy too just add this to the config
`config.active_job.queue_adapter = :sucker_punch`

**Comment by tomecho** [comment]
This "long time" was only documented in development, it might be much faster in production

**Comment by tomecho** [comment]
leaving any development on this at https://github.com/umts/probable-engine/tree/active-job-queue-adapter

**Comment by Cobchise** [comment]
Passing the wait param to the send_invoice call seems to have eliminated the problem without the need for a gem. I thoroughly tested the impact of the mailer running after the minute and it seems to have no impact on ui rendering this way.
`InvoiceMailer.send_invoice(rental).deliver_later(wait: 1.minute)`

**Comment by anmerkl** [comment]
I don't know if anybody mentioned that this only seems to be an issue for the first rental creation.
Any rentals created after the first one have no noticeable wait times.
