### ISSUE TITLE
Clean up errors

### ISSUE THREAD

**Issue by Cobchise** [umts/probable-engine#382]
We need to clean up errors across the board. Errors need to be succinct but also provide some indication as to what exactly went wrong. 

An example of this is that the inventory API has a handle errors call before returning during delete_reservations on rentals, but instead of using those errors, we dismiss them and force a generic error instead. This is poor practice, we want our errors to be helpful and specific to the problem they are referencing.

**Comment by anmerkl** [comment]
I'm assuming I'm only improving on the fact that all RuntimeErrors are generically caught and handled by this line:
`rescue_from RuntimeError, Exception, with: :render_500`

Are there any other errors that need improvements? 404? Flash errors?

**Comment by Anbranin** [comment]
Yeah rescuing from everything in the application controller is not the best idea
https://github.com/umts/umaps-rails/pull/819

**Comment by Cobchise** [comment]
Flash errors definitely need improvement, they're actually the main reason I created this issue. Most of the flash errors in the app just really aren't helpful to the user. 

A lot of the 'error-able' methods in the app actually do have detailed flash messages returning, however at some point they are abstracted or overwritten by a parent method which just dumps non-readable and non-specific rails errors to the user instead of a the original nice message such as 'Creating the rental failed because there are no available carts'.
