### ISSUE TITLE
ExecJS Program Error

### ISSUE THREAD

**Issue by Cobchise** [umts/probable-engine#387]
Upon attempting to deploy updates to the production server I experienced an issue. An error was thrown and the deployment remained unwritten.

I've narrowed the problem down, through some test deployments spoofing a production environment on my local machine and digging through subsequent files generated, to the final javascript method defined [here](https://github.com/umts/probable-engine/blob/master/app/assets/javascripts/rentals/new.js.erb#L90)

The problem was being generated when this file was being precompiled and after some research, the problem seemed to be caused by the syntax used in the method mentioned above, specifically the [arrow function](https://github.com/umts/probable-engine/blob/master/app/assets/javascripts/rentals/new.js.erb#L95) `=>`. This feature was only introduced in ES6 (Harmony JS), which currently Rails 5.0.2 does not support without additional gems and configuration ([sprockets 4 + babel for example](https://stackoverflow.com/questions/42460626/how-do-i-use-es6-es2015-in-a-ruby-on-rails-app)).

One robust way of dealing with this, and issues like it in the future would be to upgrade to rails 5.1.4 (see this PR #386) and integrate [webpacker](https://github.com/rails/webpacker) into our codebase along with nodejs but considering we have so little JS suffering from this problem it mightn't be worth the work at the moment.

Another solution is to re-write the offending code in such a way that it doesn't use the ES6 feature 'arrow function'. **(This is what I will do to solve this issue unless someone objects).**

**Comment by LiamBrandt** [comment]
This appears to be done from #389
