### ISSUE TITLE
Descriptive Forms

### ISSUE THREAD

**Issue by anmerkl** [umts/probable-engine#391]
[umaps-rails forms](https://hub.parking.umass.edu/robocalls/new) have a red asterisk next to required fields.
It'd be nice to have this in probable-engine.
As it stands, there is nothing to indicate required fields.  When required fields are left blank, instead of getting a flash error the web page just does nothing, which can be frustrating to the user.

**Comment by Anbranin** [comment]
Those are two separate issues, and I'm also not sure that putting errors in the flash is necessarily the best way to go, depending on what kinds of fields are required.

Putting `required: true` in an HTML5 field will usually not allow submission of the form at all, and in some browsers will make a popup (not JS, just HTML5 validation). This is generally regarded to not be sufficient.

Putting a red asterisk lets the user know ahead of time that the field is required. There are other ways to indicate being required, but a red asterisk is something a lot of people know.

You may also use JQuery's [validate](https://jqueryvalidation.org/) to flesh things out a little, and I find that that plugin is a little unnecessary for simple forms where the only validation is presence, but it's amazing when there are other validations in place. However, if the user has JS turned off (they could) it doesn't work.

On the back-end, I usually forgo putting such errors manually in the flash, and instead just use model validations. We can build an object, attempt to save it, have some descriptive model validations, and if the object doesn't save we can just put the object's errors.full_messages in the flash.
A good example of this: [model](https://github.com/umts/umaps-rails/blob/master/app/models/tpp/purchase.rb#L3-L17) and [controller](https://github.com/umts/umaps-rails/blob/master/app/controllers/tpp_controller.rb#L53-L55).

For flash styling one can look in `app/views/layouts/application.html.erb`

**Comment by anmerkl** [comment]
Right now, the form is not submitted at all when required fields are not filled out so lines like `rental.errors.full_messages.each { |e| flash_message :warning, e }` that would be helpful to the user don't ever do anything.

@elisacoutant are you working on this for #388 ?

**Comment by elisacoutant** [comment]
@anmerkl What you just mentioned is issue #382 , I am currently working on the help page and putting a red asterisk next to required fields on forms

**Comment by anmerkl** [comment]
Yeah I meant the red asterisks, sorry...
