### ISSUE TITLE
Fix "Rubocop/Metrics/AbcSize" issue in app/controllers/financial_transactions_controller.rb

### ISSUE THREAD

**Issue by tomecho** [umts/probable-engine#406]
Assignment Branch Condition size for create is too high. [25.61/20]

https://codeclimate.com/github/umts/probable-engine/app/controllers/financial_transactions_controller.rb#issue_5ad60b783e2bfa0001000189

**Comment by anmerkl** [comment]
Idk why I keep doing this...
