### ISSUE TITLE
Canceling rentals

### ISSUE THREAD

**Issue by jgthibodeau** [umts/probable-engine#43]
How will we handle canceling a rental?
- Will they be cancelable?
- Will there be a fee and will this fee change depending on proximity to the start date?
- Will the ability to cancel be revoked when within a certain number of days of the start date?
- Will a partially complete rental be cancelable?

**Comment by phantompatrol** [comment]
Answer, at least for the MVP. A no-show/cancelation will be invoiced at the normal rate. So, going bullet by bullet:

- As this is an Admin only app. Yes, customers will be able to contact us and cancel.
- They will be charged the whole rental, until further notice
- As this is an Admin only and we are charging the full rate when they cancel, no
- No

⚡  @cmednieks just to close the loop on the conversation
