### ISSUE TITLE
Check out/in golfcarts

### ISSUE THREAD

**Issue by jgthibodeau** [umts/probable-engine#5]
Show all rentals for the day
Maybe color code green if good to go, red if overdue?

Check out:
- show list of steps to perform
  - document damages (photos)
  - check vehicle charge level
  - confirm return time
  - print pre-filled pdf with rules
  - have both sign it
- submit

Check in:
- show list of steps to perform
  - document damages (photos)
  - sign documents?
  - plug in vehicle
- submit

**Comment by xliu3** [comment]
I will work on this!

**Comment by tomecho** [comment]
i will work in this while she works on other stuff!
