### ISSUE TITLE
Allow users to schedule rentals one day in advance

### ISSUE THREAD

**Issue by phantompatrol** [umts/probable-engine#70]
As an Admin, I would like to be able to schedule rentals day of.
As a User, I would like to be able to schedule rentals one day in advance.

**Comment by phantompatrol** [comment]
Settled on Admins will be able to schedule rentals day of, external users will be required to schedule one day in advance

**Comment by tomecho** [comment]
at least one day in advance ( `(Rental.last.start_time-Rental.last.created_at) > 1.day`) or exactly one day in advance
`advance = (Rental.last.start_time-Rental.last.created_at)
advance < 1.day && advance < 2.days`

**Comment by phantompatrol** [comment]
Perhaps I misspoke. What I meant was...

'As an administrator, I would like to be able to book reservations, even for `Date.today`'
'As a user (renter), I am required to make reservations at least one day in advance'.

**Comment by phantompatrol** [comment]
@tomecho , does that help?

**Comment by tomecho** [comment]
@phantompatrol thank you i see now

**Comment by tomecho** [comment]
@owlee label enhancement plz

**Comment by tomecho** [comment]
@owlee I closed #183 and assigned you to this one

**Comment by owlee** [comment]
Rental reservation works for today
