### ISSUE TITLE
The sessions model/module is currently inop

### ISSUE THREAD

**Issue by phantompatrol** [umts/probable-engine#71]

**Comment by tomecho** [comment]
@owlee assign me!

**Comment by tomecho** [comment]
as i understand this needs some advanced server configuration that i dont have access to.  I would like to have this working in the staging server. @phantompatrol @dfaulken @Anbranin have any of you configured shibboleth before?

**Comment by dfaulken** [comment]
Could you elaborate on what you mean by "configured Shibboleth?"

I suspect @werebus's expertise may also be relevant here.

**Comment by tomecho** [comment]
hmm this looks a bit more difficult than i thought, the application seems set up for the attributes already (you're third bullet) but I dont know how to make heroku use a rewrite rule.

**Comment by tomecho** [comment]
Needs @umayavuz, cannot get this done until he gets back

**Comment by tomecho** [comment]
Sessions work fine
