### ISSUE TITLE
Inventory check for rentals/rental_schedule

### ISSUE THREAD

**Issue by phantompatrol** [umts/probable-engine#90]
@owlee suggests adding an inventory check to the form on `rentals/rental_schedule`, specifically run when selecting dates (ajax?). Server side validations still apply.

**Comment by owlee** [comment]
-adding validation success and errors to flash with predefined feedback

**Comment by tomecho** [comment]
where is rentals/rental_schedule used? Is it still in use?

**Comment by owlee** [comment]
Nope, I scrapped it. However, I'm working on validation success and JS translations at the reservation page. @tomecho

**Comment by tomecho** [comment]
does this still need to be done @owlee or did #215 fix it

**Comment by tomecho** [comment]
im assuming this isnt mvp, it seems more like a enhancement
