### ISSUE TITLE
As an admin, I should not see upcoming rentals that were not picked up

### ISSUE THREAD

**Issue by phantompatrol** [umts/probable-engine#92]
(See Title) These rentals were essentially never picked up. Time of photo taken 7/14, note how unprocessed rentals still appear.

![screen shot 2016-07-14 at 10 33 58 am](https://cloud.githubusercontent.com/assets/129601/16843279/9373970e-49ae-11e6-9362-3f1d8b55ffe5.png)

Please move those rentals to `Past Rentals`

**Comment by cmednieks** [comment]
I will work on this
